apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: credit-backend-vs
  namespace: credit-scoring
spec:
  hosts:
    - credit-backend-svc
  http:
    - route:
        - destination:
            host: credit-backend-svc
            subset: stable
          weight: 100
        - destination:
            host: credit-backend-svc
            subset: canary
          weight: 0
