apiVersion: v1
kind: Service
metadata:
  name: credit-backend-svc
  namespace: credit-scoring
spec:
  type: ClusterIP
  selector:
    app: credit-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
