apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-backend-ingress
  namespace: credit-scoring
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: credit.local
      http:
        paths:
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: credit-backend-svc
                port:
                  number: 80
