apiVersion: v1
kind: Service
metadata:
  name: credit-frontend-svc
  namespace: credit-scoring
spec:
  type: ClusterIP
  selector:
    app: credit-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
