apiVersion: v1
kind: Service
metadata:
  name: credit-drift-svc
  namespace: credit-scoring
  labels:
    app: credit-drift-api
spec:
  selector:
    app: credit-drift-api
  ports:
    - name: http
      port: 8001
      targetPort: 8001
